sudo: true
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-v5.6.22-f9533ba-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_49d0ae5b7f7b_key -iv $encrypted_49d0ae5b7f7b_iv
  -in assets/server.key.enc -out assets/server.key -d
- wget -qO- $URL | tar xJf -
- ./heroku/install
- export PATH=./heroku/$(pwd):$PATH
before_script:
- export SFDX_DISABLE_ENCRYPTION=true
- sfdx force --help
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername
script:
- sfdx force:org:create -s -f config/workspace-scratch-def.json -a sfdx-travisci-april23-v1 
- sfdx force:source:push -u sfdx-travisci-april23-v1
- sfdx force:apex:test:run -c -r human
- sleep 2m
- sfdx force:org:delete -u sfdx-travisci-april23-v1 -p || true
